version: '3.7'
services:
  build:
    container_name: build
    image: nginx:latest
    ports:
      - "8015:8015"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/var/www/html
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8011:8011"
    command: [ "npm", "run", "dev" ]
